import { Metadata } from 'next';
import './global.scss';
import LayoutBase from './layout-base';
import type { PropsWithChildren } from 'react'
import { AppearanceProvider } from '@twa-dev/mark42';

export const metadata:Metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: PropsWithChildren<unknown>) {
  return (
    <html lang="en">
      <body>
          <LayoutBase>
            {children}
          </LayoutBase>
      </body>
    </html>
  );
}
